import { createHash } from 'node:crypto'

const SUPPORTED_TRANSFORMS = [
    /Number\.parseFloat\(value\.toPrecision\(12\)\)/u,
    /arg\.endsWith\("deg"\)/u,
    /return layer\.name/u
]

/**
 * Compiles the pinned circuit-json Zod union into a browser-neutral contract.
 */
export class CircuitJsonUpstreamSchemaCompiler {
    /**
     * Compiles every upstream element variant with deterministic ordering.
     * @param {Record<string, any>} rootSchema Pinned any_circuit_element schema.
     * @returns {{ schema: string, elementTypes: string[], schemas: Record<string, any>, defaultIdFields: Record<string, string>, idFieldExceptions: string[], variantSets: Record<string, any[]>, statistics: Record<string, number> }} Runtime contract.
     */
    static compile(rootSchema) {
        const leaves =
            CircuitJsonUpstreamSchemaCompiler.#elementLeaves(rootSchema)
        const collected = new Map()
        for (const leaf of leaves) {
            const type = CircuitJsonUpstreamSchemaCompiler.#elementType(leaf)
            if (!type) {
                throw new Error(
                    'Every upstream CircuitJSON union leaf must expose one literal type.'
                )
            }
            const compiled = CircuitJsonUpstreamSchemaCompiler.#schema(leaf)
            const serialized = JSON.stringify(compiled)
            if (!collected.has(type)) collected.set(type, new Map())
            collected.get(type).set(serialized, compiled)
        }

        const elementTypes = [...collected.keys()].sort()
        const schemas = {}
        const defaultIdFields = {}
        const idFieldExceptions = []
        let variantCount = 0
        for (const type of elementTypes) {
            const variants = [...collected.get(type).entries()]
                .sort(([left], [right]) => left.localeCompare(right))
                .map(([, schema]) => schema)
            variantCount += variants.length
            schemas[type] =
                variants.length === 1 ? variants[0] : ['u', ...variants]
            const typeLeaves = leaves.filter(
                (leaf) =>
                    CircuitJsonUpstreamSchemaCompiler.#elementType(leaf) ===
                    type
            )
            const idField = `${type}_id`
            if (
                typeLeaves.some((leaf) =>
                    CircuitJsonUpstreamSchemaCompiler.#fieldHasDefault(
                        leaf,
                        idField
                    )
                )
            ) {
                defaultIdFields[type] = idField
            }
            if (
                !typeLeaves.every((leaf) =>
                    CircuitJsonUpstreamSchemaCompiler.#fieldIsRequired(
                        leaf,
                        idField
                    )
                )
            ) {
                idFieldExceptions.push(type)
            }
        }
        return {
            schema: 'circuitjson-toolkit.upstream-schema.v1',
            elementTypes,
            schemas,
            defaultIdFields,
            idFieldExceptions,
            variantSets: CircuitJsonUpstreamSchemaCompiler.#variantSets(leaves),
            statistics: {
                elementTypeCount: elementTypes.length,
                schemaVariantCount: variantCount
            }
        }
    }

    /**
     * Returns the deterministic SHA-256 for one compiled contract body.
     * @param {Record<string, any>} contract Compiled contract.
     * @returns {string} Lowercase SHA-256.
     */
    static checksum(contract) {
        return createHash('sha256')
            .update(JSON.stringify(contract))
            .digest('hex')
    }

    /**
     * Renders the generated browser runtime module without Node imports.
     * @param {Record<string, any>} contract Compiled contract.
     * @param {Record<string, any>} provenance Pinned package provenance.
     * @returns {string} Generated ESM source.
     */
    static moduleSource(contract, provenance) {
        return [
            '// Generated by npm run sync:schema. Do not edit by hand.',
            `export const CIRCUIT_JSON_UPSTREAM_PROVENANCE=Object.freeze(${JSON.stringify(provenance)})`,
            `export const CIRCUIT_JSON_UPSTREAM_CONTRACT_SCHEMA=${JSON.stringify(contract.schema)}`,
            `export const CIRCUIT_JSON_UPSTREAM_ELEMENT_TYPES=Object.freeze(${JSON.stringify(contract.elementTypes)})`,
            `export const CIRCUIT_JSON_UPSTREAM_DEFAULT_ID_FIELDS=Object.freeze(${JSON.stringify(contract.defaultIdFields)})`,
            `export const CIRCUIT_JSON_UPSTREAM_ID_FIELD_EXCEPTIONS=Object.freeze(${JSON.stringify(contract.idFieldExceptions)})`,
            `export const CIRCUIT_JSON_UPSTREAM_VARIANT_SETS=Object.freeze(${JSON.stringify(contract.variantSets)})`,
            `export const CIRCUIT_JSON_UPSTREAM_SCHEMAS=Object.freeze(${JSON.stringify(contract.schemas)})`,
            `export const CIRCUIT_JSON_UPSTREAM_STATISTICS=Object.freeze(${JSON.stringify(contract.statistics)})`,
            ''
        ].join('\n')
    }

    /**
     * Flattens only the outer element union and discriminated unions.
     * @param {Record<string, any>} schema Candidate outer schema.
     * @returns {Record<string, any>[]} Element schema leaves.
     */
    static #elementLeaves(schema) {
        const typeName = schema?._def?.typeName
        if (typeName === 'ZodUnion') {
            return schema._def.options.flatMap((option) =>
                CircuitJsonUpstreamSchemaCompiler.#elementLeaves(option)
            )
        }
        if (typeName === 'ZodDiscriminatedUnion') {
            return [...schema._def.options].flatMap((option) =>
                CircuitJsonUpstreamSchemaCompiler.#elementLeaves(option)
            )
        }
        if (typeName === 'ZodEffects') {
            const inner = schema._def.schema
            if (
                ['ZodUnion', 'ZodDiscriminatedUnion'].includes(
                    inner?._def?.typeName
                )
            ) {
                return CircuitJsonUpstreamSchemaCompiler.#elementLeaves(
                    inner
                ).map((leaf) => ({
                    ...schema,
                    _def: { ...schema._def, schema: leaf }
                }))
            }
        }
        return [schema]
    }

    /**
     * Reads one leaf's literal type through known transparent wrappers.
     * @param {Record<string, any>} schema Element schema leaf.
     * @returns {string} Literal type or empty string.
     */
    static #elementType(schema) {
        let current = schema
        while (current?._def?.typeName === 'ZodEffects') {
            current = current._def.schema
        }
        if (current?._def?.typeName !== 'ZodObject') return ''
        const shape = current._def.shape()
        let typeSchema = shape.type
        while (
            ['ZodDefault', 'ZodOptional'].includes(typeSchema?._def?.typeName)
        ) {
            typeSchema = typeSchema._def.innerType
        }
        return typeSchema?._def?.typeName === 'ZodLiteral' &&
            typeof typeSchema._def.value === 'string'
            ? typeSchema._def.value
            : ''
    }

    /**
     * Tests whether one object field contains an upstream ZodDefault wrapper.
     * @param {Record<string, any>} schema Element schema leaf.
     * @param {string} field Field name.
     * @returns {boolean} Whether the field materializes an upstream default.
     */
    static #fieldHasDefault(schema, field) {
        const fieldSchema = CircuitJsonUpstreamSchemaCompiler.#elementField(
            schema,
            field
        )
        let current = fieldSchema
        while (current?._def) {
            const typeName = current._def.typeName
            if (typeName === 'ZodDefault') return true
            if (typeName === 'ZodOptional') {
                current = current._def.innerType
                continue
            }
            break
        }
        return false
    }

    /**
     * Tests whether every accepted parse requires one field to be supplied.
     * @param {Record<string, any>} schema Element schema leaf.
     * @param {string} field Field name.
     * @returns {boolean} Whether undefined is rejected.
     */
    static #fieldIsRequired(schema, field) {
        const fieldSchema = CircuitJsonUpstreamSchemaCompiler.#elementField(
            schema,
            field
        )
        if (!fieldSchema) return false
        return !['ZodDefault', 'ZodOptional'].includes(
            fieldSchema._def?.typeName
        )
    }

    /**
     * Reads one element-object field schema through an outer effect wrapper.
     * @param {Record<string, any>} schema Element schema leaf.
     * @param {string} field Field name.
     * @returns {Record<string, any> | undefined} Field schema.
     */
    static #elementField(schema, field) {
        let current = schema
        while (current?._def?.typeName === 'ZodEffects') {
            current = current._def.schema
        }
        return current?._def?.typeName === 'ZodObject'
            ? current._def.shape()[field]
            : undefined
    }

    /**
     * Derives the legacy public variant metadata from pinned schema fields.
     * @param {Record<string, any>[]} leaves Flattened element leaves.
     * @returns {Record<string, any[]>} Deterministic variant sets.
     */
    static #variantSets(leaves) {
        const selectors = {
            sourceComponentFtypes: [['source_component'], ['ftype']],
            pcbBoardShapes: [['pcb_board'], ['shape']],
            pcbSmtPadShapes: [['pcb_smtpad'], ['shape']],
            pcbHoleShapes: [['pcb_hole'], ['hole_shape']],
            pcbPlatedHoleShapes: [['pcb_plated_hole'], ['shape']],
            pcbPlatedHoleHoleShapes: [['pcb_plated_hole'], ['hole_shape']],
            pcbSolderPasteShapes: [['pcb_solder_paste'], ['shape']],
            pcbCutoutShapes: [['pcb_cutout'], ['shape']],
            pcbCopperPourShapes: [['pcb_copper_pour'], ['shape']],
            simulationSourceKinds: [
                ['simulation_voltage_source', 'simulation_current_source'],
                ['is_dc_source']
            ],
            simulationWaveShapes: [
                ['simulation_voltage_source', 'simulation_current_source'],
                ['wave_shape']
            ],
            simulationExperimentMethods: [
                ['simulation_experiment'],
                ['spice_options', 'method']
            ]
        }
        const variantSets = {}
        for (const [name, [types, path]] of Object.entries(selectors)) {
            let values = leaves
                .filter((leaf) =>
                    types.includes(
                        CircuitJsonUpstreamSchemaCompiler.#elementType(leaf)
                    )
                )
                .flatMap((leaf) =>
                    CircuitJsonUpstreamSchemaCompiler.#fieldValues(leaf, path)
                )
            if (name === 'simulationSourceKinds') {
                values = values.map((value) => (value ? 'dc' : 'ac'))
            }
            variantSets[name] = [...new Set(values)].sort()
            if (variantSets[name].length === 0) {
                throw new Error(
                    `Pinned upstream variant set is empty: ${name}.`
                )
            }
        }
        return variantSets
    }

    /**
     * Collects literal and enum values at one object-field path.
     * @param {Record<string, any>} schema Schema root.
     * @param {string[]} path Object-field path.
     * @returns {any[]} Accepted discriminant values.
     */
    static #fieldValues(schema, path) {
        let current = schema
        while (current?._def?.typeName === 'ZodEffects') {
            current = current._def.schema
        }
        while (
            ['ZodOptional', 'ZodDefault', 'ZodNullable'].includes(
                current?._def?.typeName
            )
        ) {
            current = current._def.innerType
        }
        if (path.length > 0) {
            if (current?._def?.typeName !== 'ZodObject') return []
            return CircuitJsonUpstreamSchemaCompiler.#fieldValues(
                current._def.shape()[path[0]],
                path.slice(1)
            )
        }
        const typeName = current?._def?.typeName
        if (typeName === 'ZodLiteral') return [current._def.value]
        if (typeName === 'ZodEnum') return [...current._def.values]
        if (['ZodUnion', 'ZodDiscriminatedUnion'].includes(typeName)) {
            return [...current._def.options].flatMap((option) =>
                CircuitJsonUpstreamSchemaCompiler.#fieldValues(option, [])
            )
        }
        return []
    }

    /**
     * Compiles one supported Zod node into the compact runtime instruction set.
     * @param {Record<string, any>} schema Zod schema node.
     * @returns {any} Compact runtime node.
     */
    static #schema(schema) {
        const definition = schema?._def
        const typeName = definition?.typeName
        switch (typeName) {
            case 'ZodAny':
            case 'ZodUnknown':
                return 'a'
            case 'ZodNever':
                return 'x'
            case 'ZodBoolean':
                CircuitJsonUpstreamSchemaCompiler.#assertNoCoercion(definition)
                return 'b'
            case 'ZodString':
                CircuitJsonUpstreamSchemaCompiler.#assertNoCoercion(definition)
                return CircuitJsonUpstreamSchemaCompiler.#string(definition)
            case 'ZodNumber':
                CircuitJsonUpstreamSchemaCompiler.#assertNoCoercion(definition)
                return CircuitJsonUpstreamSchemaCompiler.#number(definition)
            case 'ZodLiteral':
                return ['l', definition.value]
            case 'ZodEnum':
                return ['e', [...definition.values]]
            case 'ZodOptional':
            case 'ZodDefault':
                return [
                    '?',
                    CircuitJsonUpstreamSchemaCompiler.#schema(
                        definition.innerType
                    )
                ]
            case 'ZodNullable':
                return [
                    '0',
                    CircuitJsonUpstreamSchemaCompiler.#schema(
                        definition.innerType
                    )
                ]
            case 'ZodArray':
                return CircuitJsonUpstreamSchemaCompiler.#array(definition)
            case 'ZodTuple':
                return CircuitJsonUpstreamSchemaCompiler.#tuple(definition)
            case 'ZodObject':
                return CircuitJsonUpstreamSchemaCompiler.#object(definition)
            case 'ZodRecord':
                return [
                    'r',
                    CircuitJsonUpstreamSchemaCompiler.#schema(
                        definition.keyType
                    ),
                    CircuitJsonUpstreamSchemaCompiler.#schema(
                        definition.valueType
                    )
                ]
            case 'ZodUnion':
                return [
                    'u',
                    ...definition.options.map((option) =>
                        CircuitJsonUpstreamSchemaCompiler.#schema(option)
                    )
                ]
            case 'ZodDiscriminatedUnion':
                return [
                    'u',
                    ...[...definition.options].map((option) =>
                        CircuitJsonUpstreamSchemaCompiler.#schema(option)
                    )
                ]
            case 'ZodEffects':
                return CircuitJsonUpstreamSchemaCompiler.#effect(
                    schema,
                    definition
                )
            case 'ZodPipeline':
                return CircuitJsonUpstreamSchemaCompiler.#pipeline(definition)
            default:
                throw new Error(
                    `Unsupported upstream Zod construct: ${typeName}.`
                )
        }
    }

    /** @param {Record<string, any>} definition Zod definition. @returns {void} */
    static #assertNoCoercion(definition) {
        if (definition.coerce === true) {
            throw new Error('Coercing upstream Zod primitives are unsupported.')
        }
    }

    /** @param {Record<string, any>} definition String definition. @returns {any} */
    static #string(definition) {
        const checks = definition.checks.map((check) => {
            if (check.kind === 'endsWith') return ['end', check.value]
            if (check.kind === 'datetime') {
                return [
                    'dt',
                    check.precision ?? null,
                    check.offset === true,
                    check.local === true
                ]
            }
            throw new Error(
                `Unsupported upstream Zod string check: ${check.kind}.`
            )
        })
        return checks.length ? ['s', checks] : 's'
    }

    /** @param {Record<string, any>} definition Number definition. @returns {any} */
    static #number(definition) {
        const checks = definition.checks.map((check) => {
            if (check.kind === 'min') {
                return ['min', check.value, check.inclusive === true]
            }
            if (check.kind === 'max') {
                return ['max', check.value, check.inclusive === true]
            }
            throw new Error(
                `Unsupported upstream Zod number check: ${check.kind}.`
            )
        })
        return checks.length ? ['n', checks] : 'n'
    }

    /** @param {Record<string, any>} definition Array definition. @returns {any} */
    static #array(definition) {
        if (definition.exactLength) {
            return [
                'A',
                CircuitJsonUpstreamSchemaCompiler.#schema(definition.type),
                definition.exactLength.value,
                definition.exactLength.value
            ]
        }
        return [
            'A',
            CircuitJsonUpstreamSchemaCompiler.#schema(definition.type),
            definition.minLength?.value ?? null,
            definition.maxLength?.value ?? null
        ]
    }

    /** @param {Record<string, any>} definition Tuple definition. @returns {any} */
    static #tuple(definition) {
        if (definition.rest && definition.rest._def?.typeName !== 'ZodNever') {
            throw new Error('Rest-bearing upstream Zod tuples are unsupported.')
        }
        return [
            't',
            definition.items.map((item) =>
                CircuitJsonUpstreamSchemaCompiler.#schema(item)
            )
        ]
    }

    /** @param {Record<string, any>} definition Object definition. @returns {any} */
    static #object(definition) {
        if (definition.unknownKeys !== 'strip') {
            throw new Error(
                `Unsupported upstream Zod object unknown-key mode: ${definition.unknownKeys}.`
            )
        }
        const catchall = definition.catchall?._def?.typeName
        if (!['ZodNever', 'ZodUnknown'].includes(catchall)) {
            throw new Error(
                `Unsupported upstream Zod object catchall: ${catchall}.`
            )
        }
        const shape = definition.shape()
        const properties = {}
        for (const key of Object.keys(shape).sort()) {
            properties[key] = CircuitJsonUpstreamSchemaCompiler.#schema(
                shape[key]
            )
        }
        return ['o', properties]
    }

    /**
     * Compiles only explicitly understood transforms and refinements.
     * @param {Record<string, any>} schema Effects schema.
     * @param {Record<string, any>} definition Effects definition.
     * @returns {any} Compact runtime node.
     */
    static #effect(schema, definition) {
        const effect = definition.effect
        const inner = CircuitJsonUpstreamSchemaCompiler.#schema(
            definition.schema
        )
        if (effect.type === 'transform') {
            const source = String(effect.transform)
            if (/Invalid capacity/u.test(source)) return ['c', 'battery', inner]
            if (/parseAndConvertSiUnit/u.test(source)) {
                return ['c', 'siUnitTransform', inner]
            }
            if (SUPPORTED_TRANSFORMS.some((pattern) => pattern.test(source))) {
                return inner
            }
            if (/parseFloat\(val/u.test(source)) {
                throw new Error(
                    'Percentage transforms must be owned by a ZodPipeline.'
                )
            }
            throw new Error(`Unsupported upstream Zod transform: ${source}.`)
        }
        if (effect.type === 'refinement') {
            const type = CircuitJsonUpstreamSchemaCompiler.#elementType(schema)
            const refinements = new Map([
                ['simulation_voltage_probe', 'voltageProbe'],
                ['simulation_current_probe', 'currentProbe'],
                ['simulation_oscilloscope_trace', 'oscilloscopeTrace']
            ])
            const refinement = refinements.get(type)
            if (!refinement) {
                throw new Error(
                    `Unsupported upstream Zod refinement on ${type || 'unknown'}.`
                )
            }
            return ['c', refinement, inner]
        }
        throw new Error(`Unsupported upstream Zod effect: ${effect.type}.`)
    }

    /** @param {Record<string, any>} definition Pipeline definition. @returns {any} */
    static #pipeline(definition) {
        const input = definition.in
        const source = String(input?._def?.effect?.transform)
        if (
            input?._def?.typeName !== 'ZodEffects' ||
            input._def.effect?.type !== 'transform' ||
            !/val\.endsWith\("%"\)/u.test(source)
        ) {
            throw new Error('Unsupported upstream Zod pipeline transform.')
        }
        return [
            'p',
            CircuitJsonUpstreamSchemaCompiler.#schema(input._def.schema),
            CircuitJsonUpstreamSchemaCompiler.#schema(definition.out)
        ]
    }
}
